### PR TITLE
A bunch of new icons

### PR DESCRIPTION
**Pull request by natanlao**
Added icons for:
* YNAB,
* Standard Notes,
* Squarespace,
* Nexus Mods,
* ID.me, and
* Fidelity.

~~In every case except for ID.me and Nexus Mods, I downloaded the 1000x1000 icon PNG for the corresponding iOS app from [Apple Services Marketing Tools](https://tools.applemediaservices.com/).~~

Also, while I'm here, have you ever considered using ImageOptim to compress PNGs and other images losslessly? I have very little experience with iOS dev, so I'm not sure if you're already using it (or a similar tool), but I was able to reduce the size of IssuerIcons/ by 4.7MB (-50%). I've isolated those changes in 0b79349; feel free to drop them.

Thanks for you work! I love the app.

### CODE REVIEW

**Comment by natanlao** [comment]
Oof, upon pressing the "Create Pull Request" button I realize that app icons are bordered. I'll mark this as a draft and ping once I've fixed that, sorry...

**Comment by natanlao** [comment]
Okay, all fixed! (Except for Fidelity, since I couldn't find a nicer icon and don't have Photoshop to tweak it myself; feel free to drop it. I'm leaving it in since I saw similar icons in the directory.)

**Comment by FIGBERT** [comment]
ImageOptim generally isn't used to compress images in the IssuerIcons directory: see point three of [this comment](https://github.com/calleluks/Tofu/pull/60#issuecomment-768128064).

**Comment by natanlao** [comment]
Didn't know that, thanks for the context! I'll push shortly with that commit dropped.

**Comment by calleluks** [comment]
Thanks for the icons @natanlao, and sorry for taking so long to look at this!

**Pull request merged**
